# Basic Mathematical Operations
a=input('Enter the first number :')
b=input('Enter the second number: ')
a=int(a)
b=int(b)
c=int(a+b)
d=int(a-b)
e=int(a*b)
f=float(a/b)
print('Addition: ' , c)
print('Subtraction: ', d)
print('Multiplication: ' , e)
print('Division: ' , f)
